version: '3.8'
services:
  calendar-mcp:
    build: .
    container_name: calendar-mcp
    restart: unless-stopped
    
    # SSE mode command
    command: ["/app/startup.sh"]
    
    # Environment for SSE
    environment:
      - NODE_ENV=production
      - TRANSPORT=sse
      - PORT=8000
    
    # Volume for tokens (pas de mount local)
    volumes:
      - calendar-config:/app/config
      - calendar-tokens:/home/nodejs/.config/google-calendar-mcp
    
    # Port SSE
    ports:
      - "8000:8000"
    
    # Keep the rest
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.5"
    
    security_opt:
      - no-new-privileges:true
    
    user: "1001:1001"

volumes:
  calendar-config:
    driver: local
  calendar-tokens:
    driver: local
